### ISSUE TITLE
拍照出错，拍出来显示白屏，点完成奔溃

### ISSUE THREAD

**Issue by hymanme** [lijunguan/AlbumSelector#1]
小米4，android6.0.1
Log:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                                                                             at io.github.lijunguan.imgselector.cropimage.crop.CropView$CropRequest.flushToFile(CropView.java:280)
                                                                             at io.github.lijunguan.imgselector.cropimage.crop.CropView$CropRequest.into(CropView.java:268)
                                                                             at io.github.lijunguan.imgselector.cropimage.CropFragment.cropImage(CropFragment.java:138)
                                                                             at io.github.lijunguan.imgselector.cropimage.CropActivity$1.onClick(CropActivity.java:42)

**Comment by hymanme** [comment]
在5.0上正常且在6.0未能正常获取权限，需要手动获取！

**Comment by Raynor999** [comment]
@Hymanme 是小米6.0的系统导致无法自动申请运行时权限吗？   我用的Nexus6 测试的没问题，等找一个小米的试一下

**Comment by hymanme** [comment]
@lijunguan 刚拍照出现了一次可以获取拍照结果（图片），然后我第二次测试就没有了。很奇怪！

**Comment by Raynor999** [comment]
问题找到了在小米MIUI7.3 Android6.0出现概率很高，照片的width，height尽然得到的都是-1！！，导致采样率inSampleSize计算出错，使得图片太大无法显示。 现在考虑下个版本 通过ExifInterface 类 解决MIUI7.3，adnroid6.0上正常方法无法得到图片width、height的问题。@Hymanme

**Comment by hymanme** [comment]
@lijunguan 非常感谢，请问下个版本什么时候能发布？还有1.0.2好像没上传jcenter。 #
